dist: xenial
language: python
python: 3.7.6
install:
- pip install -r requirements_dev.txt
- pip install -e .
script:
- black --check python_debug/
- pytest
- pytest --cov=python_debug --cov-fail-under=100
after_success:
- coveralls