dist: xenial
language: python
python: 3.7.6
install:
- pip install -r requirements_dev.txt
- pip install -e .
script:
- black python_debug/
- pytest
- pytest --cov=python_debug
after_success:
- coveralls